### ISSUE TITLE
strange results if state 1 value equals state 2 value

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-longitudinal#11]
I think all differences should be zero, but that's not what we're seeing: 

![screenshot 2017-08-07 13 25 05](https://user-images.githubusercontent.com/192372/29044357-eb617cea-7b73-11e7-8ad1-8bbb333b8e87.png)

**Comment by nbokulich** [comment]
If you are using the tutorial data, the issue is as follows: when replicate samples for a single individual exist at `state_*`, one is randomly selected as the representative if `drop_duplicates=False`. Thus, if `state_1==state_2`, you may end up selecting slightly different sample populations.

Solution: raise an error if `state_1==state_2`. Would that be sufficient @gregcaporaso ?

The second issue is whether we should handle duplicates in a different way (e.g., have an option to raise an error if duplicates exist). The current behavior is:
* `True` drops all samples for an individual if duplicated
* `False` chooses a representative at random

Other possibilities:
* take the mean or median across replicates
* raise an error if replicates exist

**Comment by gregcaporaso** [comment]
That makes sense, thanks! 

> Solution: raise an error if state_1==state_2. Would that be sufficient @gregcaporaso ?

Perfect! 

> The second issue is whether we should handle duplicates in a different way (e.g., have an option to raise an error if duplicates exist)

I think that's a good idea. What if this parameter was a `Str % Choices` instead of a bool, with the choices: 'error', 'random', or 'drop', with 'error' being the default (so the user explicitly has to make a choice about what to do if data are duplicated).

 > Other possibilities

'median' and 'mean' are also good options that could be easily included here.
