### ISSUE TITLE
convert `metric` to a `MetadataCategory`?

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-longitudinal#67]
(unless if `MetadataCategories` ever transpire).

related to [this forum post](https://forum.qiime2.org/t/qiime-longitudinal-volatility-needs-clarification-for-p-metric/1681)

**Comment by jairideout** [comment]
`metric` can come from a feature table, right? If we made it a `MetadataCategory`, a feature table wouldn't work anymore as input because feature tables aren't "viewable" as Metadata (this is something we'd like to support someday in the framework, when there is a way to indicate which axis to treat as Metadata though).

**Comment by nbokulich** [comment]
all-seeing as always @jairideout ! Thanks for pointing that out... 

I will need to keep mulling this. For now we can just treat this with [better documentation](https://github.com/qiime2/docs/issues/236)

**Comment by nbokulich** [comment]
Closing until the day comes that feature tables can be passed as metadata. Will use better documentation for now (since `metadata tabulate` and `feature-table summarize` allow users to review available metrics from metadata or feature tables)
